In [1]:
import pandas as pd
from collections import Counter, defaultdict

# Global variables
from pretty_html_table import build_table

In [2]:
df_sdg = pd.read_pickle("../data/output/all_sdg_fixed_dst.pkl")
df_digital = pd.read_pickle("../data/dataframes/digital/all_digital.pkl")

In [3]:
df_eu_countries = pd.read_excel("../data/countries_eu.xlsx", sheet_name="EU")
df_other = pd.read_excel("../data/countries_eu.xlsx", sheet_name="rest")
lst_eu = df_eu_countries.Country.to_list()
lst_other = df_other.Country.to_list()

In [4]:
df_tot_pub = pd.read_excel("../data/total_number_pubs_2010_2022.xlsx", sheet_name=0, index_col=0)
dic_total_pubs = df_tot_pub.loc['TOT', :].to_dict()

In [5]:
# list SDG
lst_sdg = ["SDG" + str(i) for i in range(1, 18)]
# list Categories
lst_cat = ["Environment", "Society", "Economy"]
# list DST
lst_dst = list(df_sdg.columns)[30:37]
lst_dst_shortened = ['AI', 'robotics', 'IOT']

## Categories

In [6]:
d_cat = {country: defaultdict(lambda: 0) for country in lst_eu+lst_other}
d_dst = {country: defaultdict(lambda: 0) for country in lst_eu+lst_other}
d_cat_dst = {country: defaultdict(lambda: 0) for country in lst_eu+lst_other}
d_sdg = {country: defaultdict(lambda: 0) for country in lst_eu+lst_other}

# Categories + sdg
for ind, row in df_sdg.iterrows():
    lst_actors_in_row = row.CN.split(", ")
    for actor in lst_actors_in_row:
        if actor in d_cat.keys():
            for sdg in lst_sdg:
                if row[sdg]:
                    d_sdg[actor][sdg] += 1
            for cat in lst_cat:
                if row[cat]:
                    d_cat[actor][cat] += 1
# Digital
for ind, row in df_digital.iterrows():
    lst_actors_in_row = row.CN.split(", ")
    for actor in lst_actors_in_row:
        if actor in d_dst.keys():
            for dst in lst_dst:
                if row[dst]:
                    d_dst[actor][dst] += 1
# SDG-Digital
for ind, row in df_sdg[df_sdg['DST']].iterrows():
    lst_actors_in_row = row.CN.split(", ")
    for actor in lst_actors_in_row:
        if actor in d_cat_dst.keys():
            for dst in lst_dst_shortened:
                if row[dst]:
                    for cat in lst_cat:
                        if row[cat]:
                            d_cat_dst[actor][dst+"-"+cat] += 1

In [69]:
lst_tableau = []
for elem in [d_cat, d_cat_dst, d_dst, d_sdg]:
    df_tableau = pd.DataFrame.from_dict(elem, orient='index')
    df_tableau.loc["total", :] = df_tableau.sum()
    df_tableau.loc[:, 'total'] = df_tableau.index.map(dic_total_pubs)
    df_tableau.iloc[-1, -1] = sum(dic_total_pubs[x] for x in df_tableau.iloc[0:-1].index)
    lst_tableau.append(df_tableau)

In [70]:
df_tableau

,SDG5,SDG17,SDG11,SDG9,SDG8,SDG10,SDG2,SDG3,SDG16,SDG4,SDG6,SDG7,SDG12,SDG14,SDG15,SDG13,SDG1,total
Austria,1734.0,1244.0,1546.0,669.0,580.0,807.0,490.0,3339.0,1197.0,940.0,2544.0,1666.0,2287.0,2258.0,2635.0,11974.0,404.0,231305.0
Belgium,2705.0,1749.0,2777.0,851.0,917.0,1063.0,983.0,5426.0,2228.0,2079.0,5472.0,2300.0,3769.0,6514.0,4207.0,13376.0,1118.0,306655.0
Bulgaria,194.0,132.0,254.0,66.0,93.0,157.0,105.0,498.0,158.0,205.0,510.0,227.0,378.0,1000.0,524.0,1357.0,49.0,43199.0
Croatia,611.0,561.0,703.0,333.0,511.0,620.0,166.0,1502.0,566.0,617.0,1312.0,675.0,1122.0,3576.0,795.0,2752.0,150.0,61244.0
Cyprus,153.0,165.0,352.0,73.0,100.0,152.0,40.0,512.0,204.0,318.0,566.0,302.0,374.0,675.0,247.0,1079.0,47.0,23910.0
Czech Republic,1256.0,1109.0,1672.0,665.0,896.0,671.0,337.0,1914.0,1132.0,1275.0,3810.0,1090.0,2315.0,2191.0,3369.0,9676.0,346.0,221189.0
Denmark,2866.0,1113.0,1619.0,669.0,571.0,475.0,770.0,4343.0,1385.0,1462.0,4381.0,2406.0,3452.0,7941.0,2412.0,12693.0,847.0,258968.0
Estonia,450.0,172.0,245.0,145.0,131.0,86.0,66.0,382.0,204.0,246.0,576.0,307.0,413.0,1382.0,553.0,2530.0,52.0,31538.0
Finland,2435.0,981.0,2052.0,827.0,612.0,794.0,393.0,3059.0,1386.0,2094.0,4007.0,2209.0,2881.0,4668.0,3768.0,14168.0,666.0,201708.0
France,10027.0,3088.0,5668.0,1749.0,1421.0,1424.0,2683.0,16374.0,4213.0,2297.0,12430.0,5229.0,9405.0,37254.0,9200.0,51436.0,1614.0,1032632.0
Germany,12957.0,5613.0,8240.0,3674.0,3525.0,3679.0,2406.0,21067.0,7280.0,6662.0,16933.0,9420.0,14650.0,28340.0,15245.0,71501.0,2575.0,1527335.0
Greece,1920.0,843.0,2600.0,634.0,520.0,786.0,505.0,4845.0,1407.0,1160.0,5351.0,2149.0,3555.0,8511.0,2492.0,9128.0,820.0,176865.0
Hungary,477.0,371.0,1149.0,247.0,233.0,268.0,194.0,1759.0,547.0,436.0,1771.0,563.0,1127.0,827.0,1410.0,5081.0,168.0,103636.0
Ireland,1300.0,683.0,742.0,493.0,413.0,579.0,368.0,3237.0,1139.0,1176.0,2422.0,815.0,1756.0,3873.0,1353.0,4935.0,490.0,169159.0
Italy,13231.0,5440.0,13965.0,3925.0,2504.0,3886.0,3618.0,41031.0,7489.0,4515.0,23155.0,11228.0,19732.0,44134.0,19277.0,55803.0,2141.0,935654.0
Latvia,238.0,337.0,455.0,228.0,290.0,199.0,56.0,275.0,212.0,258.0,490.0,523.0,424.0,628.0,442.0,1640.0,66.0,22579.0
Lithuania,464.0,510.0,762.0,331.0,341.0,287.0,151.0,805.0,392.0,227.0,815.0,508.0,769.0,1263.0,816.0,2547.0,137.0,40094.0
Luxembourg,71.0,120.0,186.0,54.0,64.0,66.0,40.0,245.0,100.0,103.0,395.0,159.0,259.0,101.0,116.0,607.0,88.0,18517.0
Malta,78.0,68.0,48.0,23.0,19.0,35.0,1.0,150.0,62.0,57.0,52.0,64.0,77.0,382.0,61.0,235.0,19.0,6563.0
Netherlands,5421.0,4027.0,5089.0,1861.0,1715.0,2266.0,1881.0,9983.0,5192.0,4688.0,7986.0,3913.0,6992.0,11066.0,5922.0,26797.0,2151.0,559377.0
Poland,2022.0,1666.0,4229.0,1148.0,981.0,969.0,1085.0,7744.0,1589.0,1007.0,8545.0,2735.0,4404.0,7077.0,3479.0,14746.0,477.0,421235.0
Portugal,5400.0,1675.0,3545.0,1473.0,1017.0,1459.0,680.0,3884.0,1811.0,2852.0,8272.0,3020.0,6474.0,19577.0,5351.0,15549.0,562.0,227574.0
Romania,1195.0,2111.0,2676.0,1165.0,1350.0,1687.0,749.0,4447.0,2111.0,874.0,4910.0,1895.0,3533.0,2962.0,2895.0,9126.0,650.0,178996.0
Slovakia,407.0,627.0,815.0,453.0,616.0,573.0,164.0,1028.0,581.0,726.0,1202.0,480.0,884.0,437.0,1099.0,3005.0,257.0,76077.0
Slovenia,324.0,279.0,552.0,226.0,173.0,257.0,92.0,746.0,349.0,381.0,1133.0,448.0,766.0,1203.0,785.0,1887.0,84.0,58367.0
Spain,11721.0,4795.0,8995.0,3431.0,2896.0,4213.0,2330.0,19179.0,6051.0,5986.0,29487.0,8035.0,17106.0,37130.0,14329.0,54250.0,2156.0,810366.0
Sweden,5277.0,2527.0,3296.0,1273.0,1138.0,1261.0,724.0,5981.0,3022.0,2726.0,6302.0,3425.0,5079.0,9647.0,4789.0,21148.0,1515.0,393507.0
Norway,4737.0,1193.0,1334.0,696.0,622.0,834.0,453.0,3608.0,1905.0,2029.0,2483.0,1489.0,2149.0,14021.0,2377.0,15068.0,718.0,208621.0
Switzerland,3248.0,2497.0,2200.0,909.0,745.0,767.0,1064.0,7828.0,2220.0,1536.0,4745.0,2193.0,3654.0,3734.0,4874.0,20783.0,1028.0,420343.0
United Kingdom,20567.0,13572.0,12370.0,5626.0,5642.0,7076.0,4151.0,39669.0,15316.0,12099.0,17436.0,11321.0,15279.0,41156.0,19499.0,85545.0,10866.0,1791046.0
Canada,12085.0,5469.0,6238.0,2542.0,2355.0,3099.0,2369.0,22408.0,8130.0,8660.0,14726.0,5452.0,9067.0,25577.0,11528.0,54430.0,5535.0,995364.0
China,31490.0,20073.0,74457.0,19585.0,7464.0,7709.0,9296.0,71136.0,19764.0,10818.0,172987.0,80830.0,73654.0,127554.0,71531.0,242495.0,8690.0,4837793.0
United States,61361.0,31618.0,33912.0,14055.0,16096.0,10938.0,13982.0,162792.0,47907.0,67509.0,53809.0,30638.0,42218.0,128475.0,60861.0,248271.0,36302.0,5952343.0
Japan,4965.0,2963.0,4965.0,1658.0,1044.0,973.0,1444.0,16371.0,2439.0,2428.0,11124.0,6877.0,6502.0,23580.0,6894.0,31525.0,1360.0,1202009.0
South Korea,2926.0,2398.0,4157.0,1858.0,1096.0,944.0,841.0,11119.0,2109.0,1734.0,11331.0,7802.0,8040.0,17065.0,4117.0,23821.0,1560.0,796038.0
Australia,19815.0,8363.0,10098.0,4113.0,3323.0,4979.0,2896.0,20683.0,9478.0,15936.0,18399.0,8004.0,13190.0,44400.0,16441.0,61687.0,5155.0,899147.0
Israel,1138.0,372.0,868.0,230.0,221.0,337.0,349.0,4717.0,1064.0,1434.0,2075.0,451.0,1071.0,3514.0,1015.0,4537.0,362.0,207383.0
total,247266.0,130524.0,224831.0,77958.0,62235.0,66375.0,57922.0,524086.0,162339.0,169550.0,463944.0,220848.0,288807.0,673693.0,306708.0,1207188.0,91225.0,25448336.0

In [8]:
lst_df_spe = []
for df_tableau in lst_tableau:
    df_spe = df_tableau.copy(deep=True).iloc[0:-1, 0:-1]
    for col in df_spe.columns:
        for row in df_spe.index:
            df_spe.loc[row, col] = (df_tableau.loc[row, col] / df_tableau.loc[row, 'total']) / (df_tableau.loc["total", col] / df_tableau.loc["total", 'total'])
    lst_df_spe.append(df_spe)

In [ ]:
excel_path = "../img/Commission/specialization.xlsx"
with pd.ExcelWriter(excel_path) as writer:

    lst_df_spe[0].round(2).to_excel(writer, sheet_name='categories')
    lst_df_spe[1].round(2).to_excel(writer, sheet_name='cat-dt')
    lst_df_spe[2].round(2).to_excel(writer, sheet_name='dt')
    lst_df_spe[3].round(2).to_excel(writer, sheet_name='sdg')

In [11]:
# categories-DT
lst_df_spe[1]

,robotics-Economy,AI-Economy,IOT-Economy,AI-Environment,AI-Society,robotics-Environment,IOT-Society,robotics-Society,IOT-Environment
Austria,1.444287,1.277629,0.979767,0.782475,0.615130,0.596053,0.490104,1.022536,1.640386
Belgium,0.480619,0.881872,1.297796,0.620868,0.688836,0.637483,0.603159,0.825817,0.791883
Croatia,0.962603,0.819394,2.256319,1.420047,1.367119,1.713569,0.896281,0.702162,1.239075
Cyprus,3.287532,0.816211,2.080592,1.310762,2.380303,3.700700,1.846597,2.098302,4.919412
Czech Republic,0.755171,0.554591,0.624742,0.513627,0.583884,0.632616,0.323696,0.918087,0.428852
Denmark,0.417356,0.699763,0.426882,0.698891,0.439537,0.770763,0.488438,0.590421,1.128173
Estonia,0.934645,1.414391,0.525789,2.186210,0.798182,1.696423,1.059434,2.121056,1.924939
Finland,1.802346,0.732549,2.740318,0.959439,0.805771,1.009967,1.520407,0.781716,1.730596
France,0.428180,0.566967,0.701213,0.790616,0.508750,0.836949,0.773091,0.548316,0.473997
Germany,1.453897,0.916333,0.951800,0.873109,0.671092,0.758524,0.495342,0.810259,0.708014
Greece,3.944356,2.947701,4.625342,2.232708,2.094716,1.698658,2.030835,2.323351,2.724538
Hungary,0.663662,0.807039,1.013368,0.680417,0.929352,0.675093,0.575717,1.244834,1.098352
Ireland,1.161701,1.071278,1.470420,0.597500,0.870233,0.523080,1.093419,0.663790,1.637415
Italy,2.110768,1.319995,2.628868,1.406816,1.362174,2.058522,1.598033,2.410377,2.579128
Latvia,0.870332,0.493900,NaN,0.555212,0.484734,0.729089,2.061151,1.798757,1.680453
Lithuania,0.735193,1.668844,1.102896,1.348382,0.873532,1.231762,0.476201,0.774626,0.567810
Luxembourg,0.530627,1.806735,5.671619,0.677006,2.068740,0.777898,0.386661,1.935303,NaN
Netherlands,1.317396,0.662874,0.523715,0.554669,0.637854,0.489263,0.330657,0.781582,0.345937
Poland,0.583143,0.800838,0.498636,0.723550,0.750899,0.781611,0.373938,0.606859,0.405340
Portugal,3.842616,2.033617,3.376107,1.566506,1.507729,2.956788,1.615021,1.921130,2.350864
Romania,3.513147,1.837902,2.532180,1.190608,1.430807,1.322055,2.066657,1.561603,3.285636
Slovakia,1.420689,1.392560,0.944526,0.700324,0.697745,0.243436,0.360765,0.628065,0.448870
Slovenia,1.851761,0.764252,1.041716,0.765158,0.946962,0.352556,0.347561,0.532113,0.845098
Spain,1.891485,1.720175,2.196336,1.445451,1.412729,1.465175,1.391556,1.583147,2.078896
Sweden,0.823988,0.857268,1.123729,0.519675,0.508987,0.381738,0.667145,0.880326,0.742454
Norway,0.847762,1.015639,0.529903,1.179275,0.653160,1.903682,0.509075,0.664199,0.636563
Switzerland,0.631131,0.649989,0.736391,0.564784,0.714738,0.548289,0.593325,1.079886,0.595760
United Kingdom,0.954558,0.882592,0.975224,0.658812,0.737274,0.907644,0.730220,0.884372,0.735113
Canada,0.493569,0.711436,0.688595,0.989457,0.888460,0.593328,0.786451,0.643252,0.705214
China,0.775846,1.438981,0.975741,1.402212,1.591455,0.904722,1.881293,1.168411,1.110573
United States,0.884782,0.802330,0.596171,0.892979,0.904752,0.993214,0.632902,0.862535,0.719676
Japan,0.564028,0.424451,0.450653,0.540369,0.475304,1.150420,0.491414,0.711547,0.631326
South Korea,0.592471,1.120727,1.381794,1.207686,1.258731,1.088287,2.019221,0.885353,1.763596
Australia,1.125554,0.927095,1.100389,1.305343,0.935452,1.629462,0.757801,1.195666,1.227986
Israel,0.568549,0.215095,0.026653,0.355139,0.443317,0.327443,0.241672,0.426243,0.036592
Bulgaria,NaN,0.580835,0.511812,0.562252,0.772742,0.381076,0.524844,0.497734,0.878329
Malta,NaN,NaN,NaN,0.238765,1.334123,2.508318,0.181822,NaN,NaN

In [14]:
# DT
lst_df_spe[2]

,AI,computing_infrastructure,big_data,IOT,robotics,blockchain,additive_manufacturing
Austria,0.64,0.71,0.59,0.83,0.70,1.22,1.18
Belgium,0.66,0.58,0.63,0.78,0.71,0.47,0.98
Bulgaria,0.63,0.91,0.74,0.78,0.67,0.69,0.71
Croatia,0.76,0.50,0.55,0.78,0.82,1.39,0.70
Cyprus,0.98,1.08,0.99,1.53,1.07,2.65,0.47
Czech Republic,0.64,0.50,0.42,0.61,0.68,0.44,1.25
Denmark,0.47,0.48,0.46,0.46,0.57,0.66,0.57
Estonia,0.62,0.65,0.76,0.98,0.81,2.46,1.22
Finland,0.81,1.66,0.83,1.46,0.68,1.25,0.99
France,0.77,0.85,0.72,0.76,0.80,0.59,0.77
Germany,0.83,0.80,0.68,0.74,0.90,0.66,1.45
Greece,1.34,1.98,1.71,1.77,1.11,2.34,0.94
Hungary,0.73,0.76,0.70,0.56,0.75,0.53,0.86
Ireland,0.59,0.86,0.77,1.06,0.35,1.43,0.87
Italy,1.10,1.25,1.10,1.64,1.73,1.29,1.60
Latvia,0.59,0.61,0.72,1.21,0.64,1.16,0.50
Lithuania,0.64,0.53,0.51,0.57,0.80,1.25,1.25
Luxembourg,0.92,2.00,1.30,1.54,0.91,3.98,0.56
Malta,0.81,0.38,0.29,0.47,0.68,5.13,1.08
Netherlands,0.64,0.42,0.61,0.53,0.65,0.55,0.70
Poland,0.71,0.56,0.44,0.42,0.66,0.46,1.11
Portugal,1.12,1.08,0.89,1.61,1.28,1.31,1.69
Romania,0.92,1.22,0.90,1.40,1.41,1.73,1.56
Slovakia,0.70,0.49,0.66,0.67,1.09,0.73,1.69
Slovenia,0.90,0.49,0.54,0.72,0.78,1.21,1.22
Spain,1.09,1.25,0.99,1.11,1.01,0.88,1.03
Sweden,0.45,0.79,0.61,0.71,0.59,0.35,0.71
Norway,0.52,0.43,0.62,0.53,0.56,1.10,0.51
Switzerland,0.75,0.60,0.59,0.59,0.80,0.94,0.87
United Kingdom,0.72,0.66,0.73,0.68,0.64,0.86,0.85
Canada,0.76,0.78,0.70,0.74,0.72,0.86,0.66
China,1.79,1.67,1.78,1.58,1.44,1.79,1.22
United States,0.83,0.83,0.94,0.72,0.81,0.61,0.88
Japan,0.80,0.87,0.70,0.88,1.41,0.48,0.53
South Korea,1.21,1.36,1.21,2.24,1.77,1.57,1.19
Australia,0.72,0.71,0.83,0.81,0.64,1.39,0.89
Israel,0.60,0.38,0.60,0.35,0.51,0.40,0.53

##  Normalising by pop

In [32]:
eu_countries = pd.read_excel("../data/countries_eu.xlsx", sheet_name='EU').Country.to_list()
other_countries = pd.read_excel("../data/countries_eu.xlsx", sheet_name='rest').Country.to_list()
gdp = pd.read_csv("../data/countriesgdp_pop.csv", index_col="ranking")
gdp = gdp[gdp.country.isin(eu_countries + other_countries)].set_index("country")
gdp.loc["EU", "gdppc"] = 44024
gdp.loc["EU", "pop2022"] = 446800
gdp

                   gdppc      pop2022
country
Luxembourg      118001.0      647.599
Ireland          94392.0     5023.109
Switzerland      72874.0     8740.472
Norway           65800.0     5434.319
United States    63416.0   338289.857
Denmark          58932.0     5882.261
Netherlands      57534.0    17564.014
Austria          55218.0     8939.617
Sweden           54146.0    10549.347
Germany          54076.0    83369.843
Australia        51680.0    26177.413
Belgium          51096.0    11655.930
Finland          49853.0     5540.745
Canada           48720.0    38454.327
France           46062.0    64626.628
South Korea      44621.0    51815.810
United Kingdom   44117.0    67508.936
Malta            42856.0      533.286
Japan            42248.0   123951.692
Italy            40861.0    59037.474
Czech Republic   40618.0    10493.986
Israel           40547.0     9038.309
Cyprus           40107.0     1251.488
Slovenia         40067.0     2119.844
Spain            39121.0    47558.630
Estonia          38834.0     1326.062
Lithuania        38824.0     2750.055
Poland           34103.0    39857.145
Portugal         34043.0    10270.865
Hungary          33030.0     9967.308
Slovakia         32709.0     5643.453
Latvia           31509.0     1850.651
Romania          30526.0    19659.267
Greece           28748.0    10384.971
Croatia          27717.0     4030.358
Bulgaria         23817.0     6781.953
China            17192.0  1425887.337
EU               44024.0   446800.000

In [90]:
lst_tableau_normed = []

for tab in lst_tableau:
    tab_normed = tab.copy(deep=True).iloc[0:-1,0:-1]
    tab_normed.loc[:,"pop"] = tab_normed.index.map(gdp.pop2022.to_dict())
    copy_columns = list(tab_normed.columns)
    copy_columns.remove('pop')
    for col in copy_columns:
        tab_normed.loc[:,col] = tab_normed.apply(lambda x:x[col]/x['pop'], axis=1)
    tab_normed.drop(columns=['pop'], axis=1, inplace=True)
    tab_normed.loc[:,'total_per_country'] = tab_normed.loc[:,:].sum(axis=1)
    tab_normed.loc["total_per_cat", :] = tab_normed.loc[:,:].sum(axis=0)

    lst_tableau_normed.append(tab_normed)

In [91]:
lst_tableau_normed[0]

                  Society    Economy  Environment  total_per_country
Austria          1.470980   0.567027     1.876590           3.914597
Belgium          2.071306   0.667300     2.059381           4.797987
Bulgaria         0.315543   0.111620     0.422445           0.849608
Croatia          1.514009   0.671404     1.758653           3.944067
Cyprus           1.922511   0.607277     1.570131           4.099919
Czech Republic   1.182963   0.492854     1.443017           3.118834
Denmark          3.267791   1.010156     3.905301           8.183248
Estonia          1.867937   0.665881     3.357309           5.891127
Finland          3.141274   1.029103     4.063172           8.233550
France           0.905215   0.252713     1.511188           2.669117
Germany          1.006659   0.346552     1.374058           2.727269
Greece           1.918734   0.564277     1.929904           4.412916
Hungary          0.688049   0.211792     0.731792           1.631634
Ireland          2.232283   0.734605     2.008915           4.975803
Italy            1.938599   0.563490     2.010028           4.512117
Latvia           1.326020   0.722989     1.453543           3.502551
Lithuania        1.471607   0.723986     1.674876           3.870468
Luxembourg       2.047563   0.819952     1.267760           4.135275
Malta            0.958210   0.378784     1.220733           2.557727
Netherlands      2.522032   0.890913     2.479274           5.892218
Poland           0.720272   0.213713     0.630778           1.564763
Portugal         2.796551   1.088126     3.921091           7.805769
Romania          0.957208   0.434960     0.756030           2.148198
Slovakia         0.972277   0.501466     0.799511           2.273254
Slovenia         1.884573   0.729771     1.819474           4.433817
Spain            1.887292   0.631768     2.209042           4.728101
Sweden           2.914209   0.995986     3.343809           7.254003
Norway           3.322587   0.942896     5.762636          10.028119
Switzerland      2.871355   0.911736     3.343298           7.126389
United Kingdom   2.045418   0.646744     2.148204           4.840367
Canada           2.162539   0.553358     2.365846           5.081743
China            0.327359   0.084514     0.308902           0.720776
United States    1.466621   0.320568     1.283905           3.071094
Japan            0.407328   0.099014     0.498251           1.004593
South Korea      0.826582   0.261194     0.865585           1.953361
Australia        4.042111   1.202220     4.651033           9.895363
Israel           1.360874   0.234668     0.996425           2.591967
total_per_cat   64.734444  21.885376    73.821889         160.441709

In [93]:
lst_df_spe = []
for df_tableau in lst_tableau_normed:
    df_spe = df_tableau.copy(deep=True).iloc[0:-1, 0:-1]
    for col in df_spe.columns:
        for row in df_spe.index:
            df_spe.loc[row, col] = (df_tableau.loc[row, col] / df_tableau.loc[row, 'total']) / (
                        df_tableau.loc["total", col] / df_tableau.loc["total", 'total'])
    lst_df_spe.append(df_spe)

KeyError: 'total'

In [94]:
excel_path = "../img/Commission/specialization.xlsx"
with pd.ExcelWriter(excel_path) as writer:

    lst_df_spe[0].round(2).to_excel(writer, sheet_name='categories_norm_pop')
    lst_df_spe[1].round(2).to_excel(writer, sheet_name='cat-dt')
    lst_df_spe[2].round(2).to_excel(writer, sheet_name='dt_norm_pop')
    lst_df_spe[3].round(2).to_excel(writer, sheet_name='sdg_norm_pop')

IndexError: At least one sheet must be visible